version: "3.4"
services:
#backup iphotos
  icloud:
    image: mandarons/icloud-drive
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    env_file:
#      - .env.icloud #should contain ENV_ICLOUD_PASSWORD=<password>
    container_name: icloud
    restart: unless-stopped
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
#      - ${PWD}/icloud/config.yaml:/app/config.yaml
#      - ${PWD}/icloud/data:/app/icloud
#      - ${PWD}/session_data:/app/session_data


#duplicate pcloud?
  duplicati:
    image: lscr.io/linuxserver/duplicati:latest
    container_name: duplicati
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - CLI_ARGS= #optional
    volumes:
      - /docker/duplicati/config:/config
      - /docker/duplicati/backups:/backups
      - /docker/duplicati/source:/source
    ports:
      - 8200:8200
    restart: unless-stopped
