version: "3.7"
services:
# Start the agent with the latest version
  hub-agent:
    image: ghcr.io/traefik/hub-agent-traefik:latest
    container_name: hub-agent
    restart: "on-failure"
    command:
      - run
      - --hub.token=f1a1bdf2-91bb-4771-87b5-75c60cd21dd3
      - --auth-server.advertise-url=http://hub-agent
      - --traefik.host=traefik
      - --traefik.tls.insecure=true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - traefik

  # Start Traefik with the latest version
  traefik:
    image: traefik:latest
    container_name: traefik
    command:
      # Enable Hub communication (open the port 9900 and 9901 by default)
      - --experimental.hub=true
      - --hub.tls.insecure=true
      - --metrics.prometheus.addrouterslabels=true
#radarr : movies     
  radarr:
    image: lscr.io/linuxserver/radarr
    container_name: radarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - /docker/radarr/config:/config
#      - osumterra:/movies
      - /docker/downloads:/downloads #optional
    ports:
      - 7878:7878
    restart: unless-stopped

#sonarr ...tv
  sonarr:
    image: lscr.io/linuxserver/sonarr
    container_name: sonarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - /docker/sonarr/config:/config
#      - osumterra:/tv
      - /docker/downloads:/downloads #optional
    ports:
      - 8989:8989
    restart: unless-stopped
#deluge donwloader
  deluge:
    image: lscr.io/linuxserver/deluge
    container_name: deluge
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - DELUGE_LOGLEVEL=error #optional
    volumes:
      - /docker/deluge/config:/config
      - /docker/downloads:/downloads
    ports:
      - 8112:8112
      - 6881:6881
      - 6881:6881/udp
    restart: unless-stopped
#lidarr songs
  lidarr:
    image: lscr.io/linuxserver/lidarr
    container_name: lidarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - /docker/lidarr/config:/config
#     - osumterra:/music #optional
      - /docker/downloads:/downloads
    ports:
      - 8686:8686
    restart: unless-stopped
#readarr  Book Manager and Automation 
  readarr:
    image: lscr.io/linuxserver/readarr:develop
    container_name: readarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - /docker/readarr/config:/config
 #     - osumterra:/books
      - /docker/downloads:/downloads
    ports:
      - 8787:8787
    restart: unless-stopped 
#Prowlarr : indexer manager/proxy
  prowlarr:
    container_name: prowlarr
    image: lscr.io/linuxserver/prowlarr:develop
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - /docker/prowlarr/config:/config
    ports:
      - 9696:9696
    restart: unless-stopped
    
